# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Router
  config.vm.define "r1" do |r1|
    r1.vm.box = "cheretbe/routeros-long-term"
    r1.vm.hostname = 'r1'
    # port forward and private networtk
    r1.vm.network "forwarded_port", guest: 8291, host: 8291, host_ip: "127.0.0.1"
    r1.vm.network "private_network", type: "dhcp", auto_config: false, virtualbox__intnet: "red_privada"

    # upload file auto provision
    r1.vm.provision "routeros_file", name: "Upload test", source: "custom_script.rsc", destination: "custom_script.rsc"
    # execute provision 
    r1.vm.provision "routeros_command", name: "Exec custom script",
      command: "/import custom_script.rsc", check_script_error: true
  end

  # PC1
  config.vm.define "pc1" do |pc1|
    pc1.vm.box = "minimal/xenial64"
    pc1.vm.hostname = 'pc1'

    pc1.vm.network "private_network", ip: "192.168.50.2", virtualbox__intnet: "red_privada"
    pc1.vm.provision "shell",
      run: "always",
      inline: "ip ro change default via 192.168.50.1"
  end

  # PC2
  config.vm.define "pc2" do |pc2|
    pc2.vm.box = "minimal/xenial64"
    pc2.vm.hostname = 'pc2'

    pc2.vm.network "private_network", ip: "192.168.50.3", virtualbox__intnet: "red_privada"
    pc2.vm.provision "shell",
      run: "always",
      inline: "ip ro change default via 192.168.50.1"
  end
  
end
